language: node_js
branches:
  only:
  - master

script:
  - set -ev
  - export TZ='Asia/Shanghai'
  - zip -r MoeCraft-Resourcepack.zip ./*

after_success:
  - curl -T MoeCraft-Resourcepack.zip -u $CDN_USER:$CDN_PASSWD ftp://cdn.kotori.net/MoeCraft/.minecraft/resourcepacks/
