language: node_js
branches:
  only:
  - master

install:
  - git config --global user.name "Travis-CI"
  - git config --global user.email "czhdwbcg@gmail.com"

script:
  - set -ev
  - export TZ='Asia/Shanghai'
  - zip -r MoeCraft-Resourcepack.zip ./*

after_success:
# - curl -T MoeCraft-Resourcepack.zip -u $CDN_USER:$CDN_PASSWD ftp://cdn.kotori.net/MoeCraft/.minecraft/resourcepacks/

  - git clone -b master https://$GITLAB_USER:$GITLAB_PASSWD@gitlab.com/Kenvix/moxbin.git .client
  - cd .client
  - git checkout master
  - cp -f ../MoeCraft-Resourcepack.zip ./.minecraft/resourcepacks/
  - git add ./.minecraft/resourcepacks/MoeCraft-Resourcepack.zip
  - git commit -m "Travis-CI Updated Resourcepack"

  - git push origin master --force
