# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pr:
  - master

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true  # whether to fetch clean each time
  fetchDepth: 1  # the depth of commits to ask Git to fetch
  lfs: true  # whether to download Git-LFS files
  submodules: recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
- script: zip -T -r -9 MoeCraft-Resourcepack.zip ./*
  displayName: Compress MineCraft Resourcepack  # friendly name displayed in the UI
  name: compress  # identifier for this step (A-Z, a-z, 0-9, and underscore)
- script: |
    git tag -l '$(Build.SourceVersion)'
    git push --tags --progress "origin" master:master
  displayName: Make git tag  # friendly name displayed in the UI
  name: taggit  # identifier for this step (A-Z, a-z, 0-9, and underscore)
- task: GitHubRelease@0
  inputs:
    gitHubConnection: kenvix
    repositoryName: MoeNetwork/MoeCraft-Resourcepack
    action: 'create' # Options: create, edit, delete
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'auto' # Required when action == Create# Options: auto, manual
    tag: $(Build.SourceVersion) # Required when action == Edit || Action == Delete || TagSource == Manual
    title: MoeCraft ResourcePack Auto Build # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: 'MoeCraft-Resourcepack.zip' # Optional
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    isDraft: false # Optional
    #isPreRelease: false # Optional
    addChangeLog: true # Optional